version: '3'
services:
  cassandra-seed:
    image: cassandra:latest
    volumes:
      - ./cassandra/data-seed:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
    ports:
      - "9042:9042" # Exposing Cassandra default CQL port

  cassandra-node:
    image: cassandra:latest
    volumes:
      - ./cassandra/data-node:/var/lib/cassandra
    depends_on:
      - cassandra-seed
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cassandra-seed
    deploy:
      replicas: 2

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379" # Exposing Redis default port

  create-cassandra-keyspace:
    image: python
    depends_on:
      - cassandra-seed
      - cassandra-node
    entrypoint: >
      sh -c "sleep 10 ; pip install cassandra-driver; python /scripts/create_db.py "
    volumes:
      - ./scripts:/scripts


  cassandra-web:
    image: delermando/docker-cassandra-web:v0.4.0
    container_name: cassandra-web
    depends_on:
      - cassandra-node
    environment:
      - CASSANDRA_HOSTS=cassandra-seed
      - CASSANDRA_PORT=9042
      - CASSANDRA_USERNAME=user
      - CASSANDRA_PASSOWRD=pass
    ports:
      - "3000:3000"
    

  chat-service:
    build: ./chat-service
    hostname: chat-svc
    depends_on:
      - cassandra-seed
      - cassandra-node
      - redis
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CASSANDRA_HOSTS=cassandra-seed
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=chat
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    

  nginx:
    image: nginx
    depends_on:
      - chat-service
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s



volumes:
  cassandra-data-seed:
  cassandra-data-node:
  redis-data: